# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0c26a0c4cf8a5cab8cd0c38809e2f4b"
name = "trx-us-checkout-extensions"
handle = "trx-us-checkout-extensions"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "quickstart-fe50bdb4.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_shipping"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
